name: "CI"
on:
  pull_request:
  push:
jobs:
  nix-build:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
    - uses: actions/checkout@v2.3.4
      with:
        fetch-depth: 0
    - uses: cachix/install-nix-action@v13
      with:
        install_url: https://github.com/numtide/nix-flakes-installer/releases/download/nix-2.4pre20210207_fd6eaa1/install
    # Configure Nix to enable flakes
    - run: echo "experimental-features = nix-command flakes" | sudo tee -a /etc/nix/nix.conf
    - name: Build CyberChef
      run: nix-build
    - name: cp prod path
      run: |
        nix-build
        cp -r "$(readlink ./result)/build" deploy
    - name: Deploy to GitHub Pages
      if: github.ref == 'refs/heads/main'
      uses: crazy-max/ghaction-github-pages@v2
      with:
        target_branch: gh-pages
        build_dir: deploy
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
